trainer:
  lr: 0.0001
  weight_decay: 0.0001
  batch_size: 16
  epochs: 1000
  split_ratio: [0.7, 0.2, 0.1]  # train, validation, test
  device: cuda
  save_model: true

train_details:
  project_name: "world_model_project"
  name: "rssm_world_model_training"
  description: "Training configuration for the world model"
  log_by_wandb: true