defaults:
  - data: data
  - wm_model: model_config
  - train: train_config
  - test: test_config
  - _self_

mode: train

result:
  base_path: result
  normalize_path: normalize
  model_dir_path: model
  evaluation_dir_path: evaluation
  test_dir_path: test
